library 'mvn-training-library'
pipeline {
    agent any

    stages {
        stage('Run tests') {
            steps {
               buildMaven();
            }
        }
    }
    post {
        always {
            // publish html
            archiveCucumberReports();
            deleteDir();
        }
    }
}