library 'mvn-training-library'
pipeline {
    agent any

    stages {
        stage('Run tests') {
            steps {
               buildMaven();
            }
        }
    } post {
          always {
              cucumber buildStatus: 'UNSTABLE',
                      failedFeaturesNumber: 0,
                      failedScenariosNumber: 0,
                      skippedStepsNumber: 0,
                      failedStepsNumber: 0,
                      classifications: [
                              [key: 'Commit', value: '<a href="${GERRIT_CHANGE_URL}">${GERRIT_PATCHSET_REVISION}</a>'],
                              [key: 'Submitter', value: '${GERRIT_PATCHSET_UPLOADER_NAME}']
                      ],
                      reportTitle: 'mvn dava report',
                      fileIncludePattern: 'results/cucumber.json',
                      sortingMethod: 'ALPHABETICAL',
                      trendsLimit: 100
          }
      }
}