library 'mvn-training-library'
pipeline {
    agent any

    stages {
        stage('Run tests') {
            steps {
               buildMaven();
            }
        }
    }
    post {
        always {
            // publish html
            publishHTML target: [
                    allowMissing         : false,
                    alwaysLinkToLastBuild: false,
                    keepAll              : true,
                    reportDir            : 'results',
                    reportFiles          : 'cucumber-reports.html',
                    reportName           : 'Selenium spring boot training Report'
            ]
            deleteDir();
        }
    }
}